version: "3"

services:
  find-a-friend-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=find_a_friend_db_user
      - POSTGRESQL_PASSWORD=find_a_friend_db_password_123456
      - POSTGRESQL_DATABASE=find_a_friend_db
